### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by nokout** [AusDTO/biz_gov#1]
Hey All, just browsing the AusDTO organisation and came across this one.

Can someone familiar with this repo please add a readme to describe its purpose. 
@cam-grant @simonschwartz

Is it still progressing?

Happy to discuss.

**Comment by monkeypants** [comment]
I was asked to put this here as it was some work done for DTO by someone (at NICTA iirc), and published on their personal account. The work belongs to AusDTO, there was a desire to have AusDTO as the "primary source" rather than have a fork of someone else's repo.

This repo was created after the work was done, obviously it would have been better to make the AusDTO repo before the work was done and then use fork/pull-request work flow. Ready-Fire-Aim :)

**Comment by monkeypants** [comment]
(I don't really know the purpose, can't write a README)

**Comment by simonschwartz** [comment]
I'm not familiar with this repo sorry. The business contact that managed
the work was Jody Stevenson (if you needed content for the Readme)

**Comment by monkeypants** [comment]
The original repo was this one https://github.com/cam-grant/bizgov

**Comment by monkeypants** [comment]
Copyright CC-BY-AU is probably in order too.
